[package]
name = "nanogenmo"
version = "0.1.0"
authors = ["Lee Baillie <lbaillie00@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
hyper-tls = "0.1.2"
serde_json = "*"
egg-mode = "0.12.0"
chrono = "*"
